server:
  port: 8822
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jurjt?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 123456
    username: root